CREATE DATABASE SCHOOL;
USE SCHOOL;
CREATE TABLE score (score_id int NOT NULL,course_num int NOT NULL,student_num int NOT NULL, score int NOT NULL, PRIMARY KEY ( score_id ));
INSERT INTO score(score_id, course_num, student_num, score) VALUES (1, 1, 15001, 89);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (2, 1, 15002, 78);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (3, 1, 15003, 80);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (4, 1, 16004, 78);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (5, 2, 15001, 85);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (6, 2, 15002, 78);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (7, 2, 15003, 75);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (8, 2, 16004, 89);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (9, 3, 15001, 87);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (10, 3, 15002, 77);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (11, 3, 15003, 88);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (12, 3, 16004, 90);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (13, 4, 15001, 90);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (14, 4, 15002, 98);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (15, 4, 15003, 89);
INSERT INTO score(score_id, course_num, student_num, score) VALUES (16, 4, 16004, 88);
SELECT student_num AS name, COUNT(score_id) INTO OUTFILE 'out' FROM score GROUP BY student_num ORDER BY COUNT(score_id);
DROP DATABASE SCHOOL;